# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 06:04
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='\u90e8\u95e8\u7f16\u53f7')),
                ('department_name', models.CharField(max_length=20, unique=True, verbose_name='\u90e8\u95e8\u540d\u79f0')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=20, verbose_name='\u5458\u5de5\u59d3\u540d')),
                ('sex', models.CharField(choices=[('f', 'fmale'), ('m', 'male')], default='m', max_length=1, verbose_name='\u6027\u522b')),
                ('phone_number', models.CharField(max_length=20, verbose_name='phone_number')),
                ('salary_rate', models.FloatField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.Department')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Employee_type',
            fields=[
                ('employee_type_id', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='\u5458\u5de5\u79cd\u7c7b\u53f7')),
                ('employee_type', models.CharField(max_length=20, unique=True, verbose_name='\u5458\u5de5\u79cd\u7c7b')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.Employee_type'),
        ),
    ]
