# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_id',
            field=models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='\u90e8\u95e8\u7f16\u53f7'),
        ),
        migrations.AlterField(
            model_name='employee_type',
            name='employee_type_id',
            field=models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='\u5458\u5de5\u79cd\u7c7b\u53f7'),
        ),
    ]
