# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='au',
            new_name='author',
        ),
    ]
