# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_auto_20160531_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendrecord',
            name='hour',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
