# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_employee_employeeid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='salaryPerHour',
        ),
        migrations.AddField(
            model_name='employee',
            name='bankCount',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employeeId',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phoneNumber',
            field=models.CharField(max_length=20, null=True, verbose_name='\u624b\u673a\u53f7'),
        ),
    ]
