# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_remove_employee_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='sex',
            field=models.CharField(choices=[('f', 'fmale'), ('m', 'male')], default='m', max_length=1, verbose_name='\u6027\u522b'),
        ),
    ]
