# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_auto_20160531_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendrecord',
            name='end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='attendrecord',
            name='start',
            field=models.TimeField(),
        ),
    ]
