# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_auto_20160519_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='salaryPerDay',
        ),
        migrations.AddField(
            model_name='employeetype',
            name='salaryPerDay',
            field=models.FloatField(null=True, verbose_name='\u65e5\u85aa'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bankCount',
            field=models.CharField(max_length=20),
        ),
    ]
