# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_auto_20160519_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='bankCount',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
