# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_auto_20160519_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendrecord',
            name='hour',
            field=models.IntegerField(default=8),
        ),
    ]
