# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 04:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_attendrecord_hour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeetype',
            old_name='salaryPerDay',
            new_name='salaryPerHour',
        ),
    ]
