# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_auto_20160523_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='employeetype',
            name='salaryPerHour',
            field=models.FloatField(verbose_name='\u65f6\u85aa'),
        ),
    ]
