# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0011_auto_20160525_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('hour', models.IntegerField()),
                ('money', models.FloatField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.Employee')),
                ('employeeType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.EmployeeType')),
            ],
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-modifyDateTime']},
        ),
    ]
