# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0012_auto_20160525_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payroll',
            old_name='money',
            new_name='salary',
        ),
    ]
